### ISSUE TITLE
Not really good

### ISSUE THREAD

**Issue by Waxo** [alexismoreau/meteor-self-delivery#1]
We can create trucks and delete, if not used.

But we have poor informations about their state and journeys, the logs on the server can be usefull, how can i create a cluster of trucks ?

**Comment by alexismoreau** [comment]
I removed useless logs on server, but the state is stored in the trucks database.
The app doesn't support bulk truck creation, nor bulk truck management.

**Comment by Waxo** [comment]
is there a way to improve this, client side and create bulk by client ?

**Comment by alexismoreau** [comment]
Yes, we can create a checkbox and remove the button (delete & create journey) beside every truck, then add global buttons on top of the page. Then handle this by a foreach.
To create several trucks at one time, we can create an input on the top of the page, like : 
`Create : <input>number of trucks</input> trucks `
(not exactly like that lol) and then handle this by a foreach.

**Comment by Waxo** [comment]
Maybe you can, in ember we may have created a component to show trucks, and since the component have the truck object we can delete it inside the component, check for the best method to remove trucks.

**Comment by alexismoreau** [comment]
We can now create and delete several trucks at once. I added more logs on server.
